### ISSUE TITLE
[RFE] New wrapper: glusterfs_version

### ISSUE THREAD

**Issue by aravindavk** [gluster/glustercli-python#30]
What do you think of adding glusterfs_version variable to glustercli?

i.e for example...

```
from glustercli import cli
cli.glusterfs_version
```

RFE from @sac

**Comment by sac** [comment]
PR#32 should resolve the issue.

from glustercli.cli import GlusterVersion
GlusterVersion().glusterfs_version

**Comment by sac** [comment]
https://github.com/gluster/glustercli-python/pull/32
