### ISSUE TITLE
parsers.py failing to lack of checks for value existence..

### ISSUE THREAD

**Issue by projx** [gluster/glustercli-python#49]
Hi

I'm running a GlusterFS cluster which is distributed across a 3 VMs and 1 Container (Which is running on a NAS, so we can snapshot the data).  I've noticed that glustercli is not working correctly, I'm seeing the following error:

```
  File "/root/gdash-master/gdash/glustercli/cli/parsers.py", line 268, in _parse_volume_status
    nodes.append(_parse_a_node(node_el))
  File "/root/gdash-master/gdash/glustercli/cli/parsers.py", line 237, in _parse_a_node
    'inodes_total': int(node_el.find('inodesTotal').text),
AttributeError: 'NoneType' object has no attribute 'text'
```

It looks like there is an issue in the parsers.py > _parse_a_node function, there is no check for the values, its assuming all values are always present

```
    value = {
        'name': brick_path,
        'uuid': node_el.find('peerid').text,
        'online': True if node_el.find('status').text == "1" else False,
        'pid': node_el.find('pid').text,
        'size_total': int(node_el.find('sizeTotal').text),
        'size_free': int(node_el.find('sizeFree').text),
        'inodes_total': int(node_el.find('inodesTotal').text),
        'inodes_free': int(node_el.find('inodesFree').text),
        'device': node_el.find('device').text,
        'block_size': node_el.find('blockSize').text,
        'mnt_options': node_el.find('mntOptions').text,
        'fs_name': node_el.find('fsName').text,
    }
```

Which is incorrect, if you see below, there is no inodes_total or inodes_free values:

```
        <node>
          <hostname>syn-02-gfs</hostname>
          <path>/gfs</path>
          <peerid>49194ed8-1942-4bae-9efa-0deef473e714</peerid>
          <status>1</status>
          <port>49152</port>
          <ports>
            <tcp>49152</tcp>
            <rdma>N/A</rdma>
          </ports>
          <pid>43</pid>
          <sizeTotal>4123168604160</sizeTotal>
          <sizeFree>1940550733824</sizeFree>
          <device>/dev/mapper/cachedev_0</device>
          <blockSize>4096</blockSize>
          <mntOptions>rw,nodev,relatime,ssd,synoacl,space_cache=v2,auto_reclaim_space,metadata_ratio=50,subvolid=328,subvol=/@syno/CNTRS-02/data/glusterfs-k3/gfs</mntOptions>
          <fsName>btrfs</fsName>
          <inodeSize>btrfs</inodeSize>
        </node>
```

**Comment by aravindavk** [comment]
This can be handled. But I think, there is some regression issue introduced in Gluster CLI. Even `inodeSize` is wrong in the above example.

**Comment by aravindavk** [comment]
Grep the Glusterd logs for any errors to set the inodesTotal

```
grep "total_inodes" /var/log/glusterfs/glusterd.log
```

**Comment by projx** [comment]
I think this is a really specific use-case issue, and probably not something anybody would have tested for. I have Gluster running inside a container on a Synology NAS, with the volume mapped through from the Host, so I can understand why there was no iNode data:

```
root@glusterfs:/# df -i /gfs/
Filesystem             Inodes IUsed IFree IUse% Mounted on
/dev/mapper/cachedev_0      0     0     0     - /gfs
root@glusterfs:/# 
```  

But for all my other Nodes (Ubuntu 20.04) it worked out of the box.

Thanks again, and sorry for harassing you on the weekend.

**Comment by aravindavk** [comment]
> I think this is a really specific use-case issue, and probably not something anybody would have tested for. I have Gluster running inside a container on a Synology NAS, with the volume mapped through from the Host, so I can understand why there was no iNode data:
> 
> ```
> root@glusterfs:/# df -i /gfs/
> Filesystem             Inodes IUsed IFree IUse% Mounted on
> /dev/mapper/cachedev_0      0     0     0     - /gfs
> root@glusterfs:/# 
> ```
> 
> But for all my other Nodes (Ubuntu 20.04) it worked out of the box.
> 
> Thanks again, and sorry for harassing you on the weekend.

Thanks for the PR and the update.
